---
- name: Kibana | Install for {{ install_mode }}
  include_tasks: "{{ install_mode }}/main.yml"
  tags:
    - kibana_install

- name: Kibana | Service
  import_tasks: service.yml
  tags:
    - kibana_service
