---

- name: Kibana | Ensure Kibana dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0755
  loop:
    - "{{ kibana_conf_dir }}"
    - "{{ kibana_log_dir }}"
    - "{{ kibana_pid_dir }}"
    - "{{ kibana_data_dir }}"
  tags:
    - kibana_configure

- name: Kibana | Configuring Kibana
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_conf_dir }}/kibana.yml"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0644
  notify: restart kibana
  tags:
    - kibana_configure

- name: Kibana | Create systemd service
  template:
    src: kibana.service.j2
    dest: "{{ kibana_systemd_file }}"
    mode: 0644
  notify:
    - restart kibana
  tags:
    - kibana_configure
