---

elasticsearch_api_host: kibana
elasticsearch_api_port: 9200

elasticsearch_config:
  node.name: "{{ elasticsearch_api_host }}"
  network.host: _site_
  bootstrap.memory_lock: true
  node.data: true
  node.master: true
  node.ingest: false
  node.ml: false
  cluster.remote.connect: false
  http.cors.enabled: true
  http.cors.allow-origin: "*"
  xpack.security.enabled: false
  xpack.ml.enabled: false

kibana_version: 6.7.0
kibana_elasticsearch_hosts: ['http://{{ elasticsearch_api_host }}:{{ elasticsearch_api_port }}']