---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kibana
    hostname: kibana
    image: idealista/jdk:8u222-stretch-openjdk-headless
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - kibana_group
    tmpfs:
      - '/run'
      - '/run/lock'
    command: '/lib/systemd/systemd'
    networks:
      - name: kibana-network
        aliases:
          - kibana
    published_ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: oss
verifier:
  name: goss
  lint:
    name: yamllint
