---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kibana
    hostname: kibana
    image: idealista/jdk:8u181-stretch-openjdk-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/sys/fs/fuse/connections:/sys/fs/fuse/connections:ro'
      - '/dev/hugepages:/dev/hugepages'
    groups:
      - kibana_group
    tmpfs:
      - '/tmp'
      - '/run'
      - '/run/lock'
    devices:
      - '/dev/fuse:/dev/fuse'
    command: '/lib/systemd/systemd'
    networks:
      - name: kibana-network
        aliases:
          - kibana
    published_ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: oss
verifier:
  name: goss
  lint:
    name: yamllint