---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: kibana
    hostname: kibana
    image: ${MOLECULE_DISTRO:-idealista/jdk:11.0.14-buster-openjdk-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - kibana_group
    tmpfs:
      - '/run'
      - '/run/lock'
    command: '/lib/systemd/systemd'
    networks:
      - name: kibana-network
        aliases:
          - kibana
    published_ports:
      - 9200:9200
      - 5601:5601
provisioner:
  name: ansible
  inventory:
    group_vars:
      kibana_group:
        java_open_jdk_home: ${JAVA_JDK_HOME:-/usr/lib/jvm/java-11-openjdk-amd64}
        kibana_version: ${KIBANA_VERSION:-7.17.4}
  env:
    ANSIBLE_FORCE_COLOR: 1
    PY_COLORS: 1
verifier:
  name: ansible
