---

version: 7.2.0
elasticsearch_version: "{{ version }}"
elasticsearch_api_host: kibana
elasticsearch_api_port: 9200
elasticsearch_license_type: oss
elasticsearch_config:
  node.name: "{{ elasticsearch_api_host }}"
  network.host: _site_
  bootstrap.memory_lock: true
  node.data: true
  node.master: true
  node.ingest: true
  discovery.type: single-node
  cluster.remote.connect: false
  http.cors.enabled: true
  http.cors.allow-origin: "*"

kibana_version: "{{ version }}"
kibana_oss_version: true
kibana_user: kibana
kibana_group: kibana
kibana_elasticsearch_hosts: ['http://{{ elasticsearch_api_host }}:{{ elasticsearch_api_port }}']
