---
install_mode: deb
install_opendistro: true
kibana_version: 7.17.4
kibana_license_type: basic

elasticsearch_api_host: kibana
elasticsearch_api_port: 9200

kibana_elasticsearch_hosts: ['http://{{ elasticsearch_api_host }}:{{ elasticsearch_api_port }}']
## Elastic
elasticsearch_service_dropin_template: "{{ playbook_dir }}/templates/elasticsearch/service.conf"

elasticsearch_config:
  node.name: "{{ elasticsearch_api_host }}"
  cluster.name: idealista-cluster
  network.host: _site_
  discovery.type: single-node
  http.port: "{{ elasticsearch_api_port }}"
  bootstrap.memory_lock: true
  node.data: true
  node.master: true
  node.ingest: false
  opendistro_security.disabled: "true"
  opendistro_security.ssl.http.enabled: "false"

elasticsearch_heap_size: "256m"
elasticsearch_os_tuning: false
