---

- name: Kibana | Ensure Kibana dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    recurse: yes
  loop:
    - "{{ kibana_conf_dir }}"
    - "{{ kibana_log_dir }}"
    - "{{ kibana_pid_dir }}"
    - "{{ kibana_data_dir }}"
    - "{{ kibana_home }}"
  tags:
    - kibana_configure

- name: Create and config drop-in service config
  when: kibana_service_dropin_template is defined
  tags:
    - kibana_configure
  block:
    - name: Create kibana drop-in service config
      file:
        path: "{{ kibana_service_config_path }}"
        owner: "{{ kibana_user }}"
        group: "{{ kibana_group }}"
        mode: 0755
        state: directory

    - name: Add drop-in file config to elastic service
      template:
        src: "{{ kibana_service_dropin_template }}"
        dest: "{{ kibana_service_config_path }}/{{ kibana_service_dropin_template | basename }}"
        owner: "{{ kibana_user }}"
        group: "{{ kibana_group }}"
        mode: 0644

- name: Kibana | Configuring Kibana
  template:
    src: "{{ item }}"
    dest: "{{ kibana_conf_dir }}/{{ item | basename | regex_replace('.j2', '') }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0644
  loop: "{{ kibana_config_templates_files }}"
  notify: Restart kibana
  tags:
    - kibana_configure
