---
- name: Kibana | Installing dependencies
  apt:
    name: "{{ kibana_required_libs }}"
    state: present
    update_cache: true

- name: Kibana | Include vars elasticco
  include_vars: vars/elasticco.yml

- name: Kibana | Define kibana variables
  set_fact:
    kibana_ppa_source: "{{ lookup('vars', '__kibana_ppa_source_' ~  kibana_license_type) }}"

- name: Kibana | Add gpg key
  apt_key:
    url: "{{ kibana_gpg_key }}"
    state: present

- name: Kibana | Add ppa repository
  apt_repository:
    repo: "{{ kibana_ppa_source }}"
    state: present
    filename: kibana

- name: Kibana | Install kibana {{ kibana_version }}
  apt:
    name: "{{ item }}={{ kibana_version }}"
    update_cache: true
    state: "{{ kibana_package_state }}"
  loop:
    - "{{ (kibana_license_type == 'oss') | ternary('kibana-oss', 'kibana') }}"
