---
- name: Kibana | Installing dependencies
  apt:
    name: "{{ kibana_required_libs }}"
    state: present
    update_cache: true
  tags:
    - kibana_install

- name: Kibana | Add gpg key
  apt_key:
    url: "{{ kibana_gpg_key }}"
    state: present
  tags:
    - kibana_install

- name: Kibana | Add ppa repository
  apt_repository:
    repo: "{{ kibana_ppa_source }}"
    state: present
    filename: kibana
  tags:
    - kibana_install

- name: Kibana | Install kibana {{ kibana_version }}
  apt:
    name: "kibana={{ kibana_version }}"
    update_cache: true
    state: "{{ kibana_package_state }}"
  tags:
    - kibana_install
