---
- name: Kibana | Include vars for opendistro
  include_vars: vars/opendistro.yml
  tags:
    - kibana_install

- name: Kibana | Installing dependencies
  apt:
    name: "{{ kibana_required_libs }}"
    state: present
    update_cache: true
  tags:
    - kibana_install

- name: Kibana | Add gpg key
  apt_key:
    url: "{{ opendistro_gpg_key }}"
    state: present
  tags:
    - kibana_install

- name: Kibana | Add ppa repository
  apt_repository:
    repo: "{{ opendistro_ppa_source }}"
    state: present
    filename: elasticsearch_opendistro
  tags:
    - kibana_install

- name: Kibana | Install kibana_opendistro {{ opendistro_version }}
  apt:
    name: "opendistroforelasticsearch-kibana={{ opendistro_version }}"
    update_cache: true
    state: "{{ opendistro_package_state }}"
  notify: restart kibana
  tags:
    - kibana_install
