---
- name: Kibana | Include vars for {{ install_mode }}
  include_vars: vars/{{ install_mode }}.yml

- name: Kibana | Install
  include_tasks: install.yml
  tags:
    - kibana_install

- name: Kibana | Configure
  include_tasks: config.yml
  tags:
    - kibana_configure
